### ISSUE TITLE
Change format a bit

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#25]
One of the things I love about the workshop is that the launch-in-editor functionality makes it easy for people to get to the right file for the exercise.

One thing I don't like at all though is that they have to close the old file and open the new one, even if it's basically the same file.

An idea I had is what if we have a "playground" directory where we simply copy the contents of the `problem` app that we're working on so they always have the same files open, but we just keep the contents up-to-date with the exercise problem they're working on. It's possible the server wouldn't have to be stopped either (and if it crashed we could auto-restart it maybe?).

I think I'd like to explore doing this because I think it would make following the exercises even easier.

**Comment by onemen** [comment]
Regarding playground folder, we can use two playground, first for problem and second for solution.
Then we can always keep two servers running. 
If we can use one port for the solution and change process.cwd() to each solution we can skip the copy step for solutions.

We can add some observer to restart the server if it crash.
We can add some messaging between 5639 server and the apps servers.
Maybe we can use child process fork for this. 

With the playground as the only folder that change we can simply maintain the starting diff.

The problem is how prevent accidental overwrite of the folder if the user navigate to different instructions page during lesson.
I think that there should be a button on the lesson page that show some notification warning before coping the files

**Comment by kentcdodds** [comment]
> The problem is how prevent accidental overwrite of the folder if the user navigate to different instructions page during lesson.

Yeah, this is a tricky one. I think there's a difference between: "I'm working on this" and "I'm just navigating around." I'm not certain of the best way to avoid issues with that. I'm thinking a "start exercise" button somewhere would make sense.

**Comment by onemen** [comment]
We can make "playground" folder a git folder, as sub-repository or on different folder, and create branch with tag for each problem step.
with that in place navigation between steps is just using `checkout STEP_BRANCH_NAME`, if the user have uncommitted changes we can automatically do `git commit` to the current brunch.
for each step we add two links one to `checkout STEP_BRANCH_NAME` and the other to `checkout STEP_TAG_NAME` that will always point to the initial state of the step

I've tested a script to create the "playground" folder for `web-app-fundamentals` and It took less than 30 seconds to finished it. And I am sure it can be faster.

**Comment by onemen** [comment]
![folder_tree](https://user-images.githubusercontent.com/3650909/230704208-d9d69693-f016-4ad3-b9e5-05e87fcd31c9.png)

You don't need to maintain changes in exercises to the brunches. you publish to complicity different repo. users will only download/install from the production ready workshop. you even publish to npm, then users can run
`npm install web-app-fundamentals`

**Comment by kentcdodds** [comment]
Interesting. So it's like some kind of build that generates the git repo based on the exercises as source files? I worry that would be more magic than I want. I think what we have with the playground is easier to understand and that's useful.

Thanks though!

I've finished the playground support, so I'm going to close this now.
